// Sprite art data for avatars: the body styles and accessory overlays.
// Pure data — the logic that reads it lives in avatar.go.
package game

// avatarStyles are the selectable body shapes. Index 0 ("claude") is the
// default: a rounded, warm-coral critter inspired by the Claude mark.
var avatarStyles = []avatarStyle{
	{
		Name: "claude",
		front: [2][]string{
			{
				"....LLLL....",
				"..LLLLLLLL..",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBWEBBBBWEBB",
				"BBEEBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				"....LLLL....",
				"..LLLLLLLL..",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBWEBBBBWEBB",
				"BBEEBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
		back: [2][]string{
			{
				"....LLLL....",
				"..LLLLLLLL..",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				"....LLLL....",
				"..LLLLLLLL..",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
		side: [2][]string{
			{
				"....LLLL....",
				"..LLLLLLLL..",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBWEBBB",
				"BBBBBBBEEBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				"....LLLL....",
				"..LLLLLLLL..",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBWEBBB",
				"BBBBBBBEEBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
	},
	{
		Name: "cat",
		front: [2][]string{
			{
				"..LL....LL..",
				".LLLL..LLLL.",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBWEBBBBWEBB",
				"BBEEBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				"..LL....LL..",
				".LLLL..LLLL.",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBWEBBBBWEBB",
				"BBEEBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
		back: [2][]string{
			{
				"..LL....LL..",
				".LLLL..LLLL.",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				"..LL....LL..",
				".LLLL..LLLL.",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
		side: [2][]string{
			{
				"..LL....LL..",
				".LLLL..LLLL.",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBWEBBB",
				"BBBBBBBEEBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				"..LL....LL..",
				".LLLL..LLLL.",
				".LLLLLLLLLL.",
				".LBBBBBBBBL.",
				"BBBBBBBBBBBB",
				"BBBBBBBWEBBB",
				"BBBBBBBEEBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
	},
	{
		Name: "bot",
		front: [2][]string{
			{
				".....LL.....",
				".....BB.....",
				"LLLLLLLLLLLL",
				"LBBBBBBBBBBL",
				"BBBBBBBBBBBB",
				"BEEBBBBBBEEB",
				"BEEBBBBBBEEB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BBBBBBBBBBBB",
				"DDDBBBBBBDDD",
				"DD......DD..",
			},
			{
				".....LL.....",
				".....BB.....",
				"LLLLLLLLLLLL",
				"LBBBBBBBBBBL",
				"BBBBBBBBBBBB",
				"BEEBBBBBBEEB",
				"BEEBBBBBBEEB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BBBBBBBBBBBB",
				"DDDBBBBBBDDD",
				".DD......DD.",
			},
		},
		back: [2][]string{
			{
				".....LL.....",
				".....BB.....",
				"LLLLLLLLLLLL",
				"LBBBBBBBBBBL",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"DDDBBBBBBDDD",
				"DD......DD..",
			},
			{
				".....LL.....",
				".....BB.....",
				"LLLLLLLLLLLL",
				"LBBBBBBBBBBL",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"DDDBBBBBBDDD",
				".DD......DD.",
			},
		},
		side: [2][]string{
			{
				".....LL.....",
				".....BB.....",
				"LLLLLLLLLLLL",
				"LBBBBBBBBBBL",
				"BBBBBBBBBBBB",
				"BBBBBBBBEEBB",
				"BBBBBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BBBBBBBBBBBB",
				"DDDBBBBBBDDD",
				"DD......DD..",
			},
			{
				".....LL.....",
				".....BB.....",
				"LLLLLLLLLLLL",
				"LBBBBBBBBBBL",
				"BBBBBBBBBBBB",
				"BBBBBBBBEEBB",
				"BBBBBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BBBBBBBBBBBB",
				"DDDBBBBBBDDD",
				".DD......DD.",
			},
		},
	},
	{
		Name: "frog",
		front: [2][]string{
			{
				".EE....EE...",
				".EW....WE...",
				".LLLLLLLLLL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BmmmmmmmmmmB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				".EE....EE...",
				".EW....WE...",
				".LLLLLLLLLL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BmmmmmmmmmmB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
		back: [2][]string{
			{
				".BB....BB...",
				".BB....BB...",
				".LLLLLLLLLL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				".BB....BB...",
				".BB....BB...",
				".LLLLLLLLLL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
		side: [2][]string{
			{
				"......EE....",
				"......EW....",
				".LLLLLLLLLL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBmmmmmBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"..D......D..",
			},
			{
				"......EE....",
				"......EW....",
				".LLLLLLLLLL.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBmmmmmBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DDBBBBBBDD.",
				"...D....D...",
			},
		},
	},
	{
		Name: "slime",
		front: [2][]string{
			{
				"............",
				"...LLLLLL...",
				"..LLLLLLLL..",
				".BBBBBBBBBB.",
				"BBBBBBBBBBBB",
				"BBWEBBBBWEBB",
				"BBEEBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DD.DD.DD.D.",
			},
			{
				"............",
				"...LLLLLL...",
				"..LLLLLLLL..",
				".BBBBBBBBBB.",
				"BBBBBBBBBBBB",
				"BBWEBBBBWEBB",
				"BBEEBBBBEEBB",
				"BBBBBBBBBBBB",
				"BBBBmmmmBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".D.DD.DD.DD.",
			},
		},
		back: [2][]string{
			{
				"............",
				"...LLLLLL...",
				"..LLLLLLLL..",
				".BBBBBBBBBB.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DD.DD.DD.D.",
			},
			{
				"............",
				"...LLLLLL...",
				"..LLLLLLLL..",
				".BBBBBBBBBB.",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".D.DD.DD.DD.",
			},
		},
		side: [2][]string{
			{
				"............",
				"...LLLLLL...",
				"..LLLLLLLL..",
				".BBBBBBBBBB.",
				"BBBBBBBBBBBB",
				"BBBBBBBWEBBB",
				"BBBBBBBEEBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".DD.DD.DD.D.",
			},
			{
				"............",
				"...LLLLLL...",
				"..LLLLLLLL..",
				".BBBBBBBBBB.",
				"BBBBBBBBBBBB",
				"BBBBBBBWEBBB",
				"BBBBBBBEEBBB",
				"BBBBBBBBBBBB",
				"BBBBBBBmmBBB",
				"BBBBBBBBBBBB",
				"BDBBBBBBBBDB",
				".D.DD.DD.DD.",
			},
		},
	},
}

// accessories overlay the head's top rows (H accessory, H shade h). Index 0 is
// "none". Overlays are 12 wide; spaces leave the underlying pixel untouched.
// Hex is the accessory's own color (worn, on the ground, and as an inventory
// icon all share it); an empty Hex falls back to the default gold. Append new
// accessories at the end — indices are persisted in saved avatars. "things like
// flowers" (flower, shroom) are nature wearables found alongside the hats.
var accessories = []struct {
	Name    string
	Hex     string
	overlay []string
}{
	{"none", "", nil},
	{"cap", "#6FB7FF", []string{
		"            ",
		"..HHHHHHHH..",
		".hhhhhhhhhh.",
	}},
	{"crown", "#FFD166", []string{
		"H..HH..HH..H",
		".HHHHHHHHHH.",
	}},
	{"band", "#FF8FB1", []string{
		"            ",
		"            ",
		".HHHHHHHHHH.",
	}},
	{"horns", "#E27396", []string{
		"H..........H",
		"HH........HH",
	}},
	{"halo", "#F2E9A0", []string{
		"...HHHHHH...",
		"..H......H..",
	}},
	{"flower", "#FF7AA8", []string{
		"..H.........",
		".HhH........",
		"..H.........",
	}},
	{"shroom", "#C792EA", []string{
		"...HHHHHH...",
		"..HHHHHHHH..",
		"...hhhhhh...",
	}},
	// A gem circlet, won by carrying a geode up out of the deep.
	{"circlet", "#9CE0FF", []string{
		"            ",
		"     HH     ",
		"..hhHHHHhh..",
	}},
	// An ancient jeweled diadem, won by bearing a relic back to the light.
	{"diadem", "#C9B0FF", []string{
		"....HH......",
		"..HHHHHHHH..",
		".HhHHHHHHhH.",
	}},
}
